package com.geektrust.family.dto;

public enum Relationship {

    PATERNAL_UNCLE, MATERNAL_UNCLE, PATERNAL_AUNT, MATERNAL_AUNT, SISTER_IN_LAW, BROTHER_IN_LAW, //
    COUSIN, FATHER, MOTHER, CHILDREN, SON, DAUGHTER, BROTHER, SISTER, GRAND_DAUGHTER

}
